	.align 2
gText_ConfirmSave::
	.string "Would you like to save the game?$"

gText_AlreadySavedFile::
	.string "There is already a saved file.\n"
	.string "Is it okay to overwrite it?$"

gText_SavingDontTurnOff::
	.string "Saving…\n"
	.string "Don't turn off the power.$"

gText_PlayerSavedGame::
	.string "{PLAYER} saved the game.$"

gText_DifferentSaveFile::
	.string "Warning!\p"
	.string "You are about to overwrite a\n"
	.string "previous save game file,\l"
	.string "which will permanently delete it.\p"
	.string "Consider making a backup of your\n"
	.string ".sav file, which can be found in\l"
	.string "the same folder as the .gba file,\l"
	.string "if you wish to prevent this.\p"
	.string "Continue?$"

gText_SaveError::
	.string "Save error.\p"
	.string "Please exchange the\n"
	.string "backup memory.$"

gText_SavingDontTurnOffPower::
	.string "Saving…\n"
	.string "Don't turn off the power.$"
